name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.0.5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - run: flutter --version
      - run: flutter analyze
      - run: flutter test
      - run: dart format . --set-exit-if-changed

  code-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage --machine > test-results.json

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: test-results.json
          reporter: dart-json

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  android-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - run: flutter pub get
        working-directory: example

      - run: flutter gen-l10n
        working-directory: example

      - run: flutter pub run crowdin_sdk:gen
        working-directory: example

      - run: flutter build apk
        working-directory: example

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: example/build/app/outputs/flutter-apk/app-release.apk
