name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.0.5'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - run: flutter --version
      - run: flutter analyze
      - run: flutter test

  android-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - run: flutter pub get
        working-directory: example

      - run: flutter gen-l10n
        working-directory: example

      - run: flutter pub run crowdin_sdk:gen
        working-directory: example

      - run: flutter build apk
        working-directory: example

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: example/build/app/outputs/flutter-apk/app-release.apk
